import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1A1A1A',
  },
  subHeader: {
    color: '#8FD3A7',
    fontSize: 16,
    textAlign: 'center',
    marginVertical: 10,
  },
  veterinarioCard: {
    backgroundColor: '#333',
    borderRadius: 12,
    padding: 10,
    width: width * 0.9,
    alignSelf: 'center',
    position: 'relative',
    overflow: 'hidden',
    height: '70%',
    marginTop: 170,
  },
  veterinarioFoto: {
    width: '100%',
    height: '50%',
    borderRadius: 12,
    resizeMode: 'cover',
  },
  infoContainer: {
    padding: 10,
  },
  veterinarioNome: {
    color: '#fff',
    fontSize: 22,
    fontWeight: 'bold',
  },
  veterinarioEspecialidade: {
    color: '#A8A8A8',
    fontSize: 16,
    marginVertical: 4,
  },
  veterinarioDetalhes: {
    color: '#A8A8A8',
    fontSize: 16,
    marginTop: 5,
  },
  experienciaText: {
    color: '#B8B8B8',
    fontSize: 14,
    marginTop: 8,
  },
  avaliacaoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 5,
  },
  avaliacaoText: {
    color: '#FFD700',
    fontSize: 14,
    marginLeft: 5,
  },
  favoritoIcon: {
    position: 'absolute',
    top: 10,
    right: 10,
  },
  noMoreContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  noMoreText: {
    color: '#fff',
    fontSize: 18,
    marginBottom: 20,
  },
  refreshButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#68D391',
    padding: 15,
    borderRadius: 25,
  },
  refreshText: {
    color: '#fff',
    fontSize: 16,
    marginLeft: 10,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: 10,
  },
  redoButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFA500',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 10,
    width: '30%',
    justifyContent: 'center',
    marginRight: 10,
  },
  contactButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#68D391',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 10,
    width: '30%',
    justifyContent: 'center',
    marginRight: 10,
  },
  scheduleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FF6347',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 10,
    width: '30%',
    justifyContent: 'center',
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    marginLeft: 5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '80%',
    backgroundColor: '#333',
    padding: 20,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 10,
  },
  modalText: {
    color: '#fff',
    fontSize: 16,
    marginBottom: 20,
    textAlign: 'center',
  },
  modalButton: {
    backgroundColor: '#8FD3A7',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  modalButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
});
  